image: lorisleiva/laravel-docker

stages:
  - deploy

before_script:
  - composer install --no-dev --prefer-dist --optimize-autoloader
  - cp .env.example .env
  - php artisan key:generate
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache

deploy_production:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R ./ /public_html"
  only:
    - main
