image: lorisleiva/laravel-docker

stages:
  - deploy

variables:
  FTP_HOST: ftp://4topiso.com
  FTP_USER: u120706926
  FTP_PASS: German354# # Asegúrate de que esta variable esté definida en las variables de CI/CD en GitLab

before_script:
  - composer install --no-dev --prefer-dist --optimize-autoloader
  - echo "APP_NAME=$APPNAME" > .env
  - echo "APP_ENV=$APPENV" >> .env
  - echo "APP_KEY=$APPKEY" >> .env
  - echo "APP_DEBUG=$APPDEBUG" >> .env
  - echo "APP_URL=$APPURL" >> .env
  - echo "DB_CONNECTION=$DBCONNECTION" >> .env
  - echo "DB_HOST=$DBHOST" >> .env
  - echo "DB_PORT=$DBPORT" >> .env
  - echo "DB_DATABASE=$DBDATABASE" >> .env
  - echo "DB_USERNAME=$DBUSERNAME" >> .env
  - echo "DB_PASSWORD=$DBPASSWORD" >> .env
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache

deploy_production:
  stage: deploy
  script:
    # Usar lftp directamente en el script
    - apk add --no-cache lftp  # Instalar lftp si estás usando Alpine Linux
    - lftp -c "open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R ./ /public_html"
  only:
    - master
